[package]
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
description = "Mavlink Camera Manager"
edition = "2021"
license = "MIT"
name = "mavlink-camera-manager"
version = "0.2.4"

documentation = "https://github.com/patrickelectric/mavlink-camera-manager"
homepage = "https://github.com/patrickelectric/mavlink-camera-manager"
readme = "README.md"
repository = "https://github.com/patrickelectric/mavlink-camera-manager"

default-run = "mavlink-camera-manager"
path = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
bench = false
name = "mavlink-camera-manager"
path = "src/main.rs"

[dependencies]
clap = "2"
regex = "1.5.4"

#TODO: Investigate rweb to use openapi spec for free
# https://github.com/kdy1/rweb
actix-files = "0.5.0"
actix-web = "3.3.3"
serde = "1.0.133"
serde_derive = "1.0.133"
serde_json = "1.0.75"

## FINAL
sys-info = "0.9.1"
chrono = "0.4.19"
env_logger = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.16"
paperclip = { version = "0.6.1", features = ["actix", "swagger-ui", "url"] }
#TODO: Replace it with yaserde
quick-xml = { version = "0.22.0", features = ["serialize"] }
simple-error = "0.2.3"
url = { version = "2.2.2", features = ["serde"] }
v4l = "0.12.1"
directories = "4.0.1"
pnet = "0.29.0"
semver = "1.0.7"

## Mavlink
mavlink = { version = "0.10.0", features = ["default", "emit-extensions"] }

## GSTREAMER
glib = { version = "0.15.2", optional = true }
gstreamer = { version = "0.18.1", optional = true }
gstreamer-rtsp-server = { version = "0.18.0", optional = true }

## WebRTC Turn/Stun and Signalling server
anyhow = "1"
async-std = "1"
async-native-tls = "0.4"
tokio = "1.19"
turn = "0.5"
util = { package = "webrtc-util", version = "0.5", default-features = false, features = ["vnet"] }
webrtcsink-signalling = { version = "0.1.0", git = "https://github.com/centricular/webrtcsink", rev = "2c855b9cfe1cf10c7447aa6ca5e3d5444e2459e0" }

[dev-dependencies]
rand = "0.8.4"

[build-dependencies]
reqwest = { version = "0.11.9", features = ["blocking"] }
vergen = { version = "6.0.0", default-features = false, features = ["build", "git"] }

[features]
default = ["rtsp"]
gst = ["glib", "gstreamer"]
rtsp = ["gst", "gstreamer-rtsp-server"]
