[package]
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
description = "Mavlink Camera Manager"
edition = "2021"
license = "MIT"
name = "mavlink-camera-manager"
version = "0.2.4"

documentation = "https://github.com/patrickelectric/mavlink-camera-manager"
homepage = "https://github.com/patrickelectric/mavlink-camera-manager"
readme = "README.md"
repository = "https://github.com/patrickelectric/mavlink-camera-manager"

default-run = "mavlink-camera-manager"
path = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
bench = false
name = "mavlink-camera-manager"
path = "src/main.rs"

[dependencies]
clap = "2"
regex = "1.6.0"

#TODO: Investigate rweb to use openapi spec for free
# https://github.com/kdy1/rweb
actix-files = "0.6.2"
actix-web = "4.1.0"
actix-service = "2.0.2"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"

## FINAL
sys-info = "0.9.1"
chrono = "0.4.19"
lazy_static = "1.4.0"
paperclip = { version = "0.7.0", features = ["paperclip-actix", "actix4", "swagger-ui", "url"] }
#TODO: Replace it with yaserde
quick-xml = { version = "0.23.0", features = ["serialize"] }
simple-error = "0.2.3"
url = { version = "2.2.2", features = ["serde"] }
v4l = "0.12.1"
directories = "4.0.1"
pnet = { version = "0.31.0", features = ["std"] }
semver = "1.0.12"
tracing = { version = "0.1.36", features = ["log", "async-await"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
tracing-log = "0.1.3"
tracing-appender = "0.2.2"
tracing-actix-web = "0.6.0"
anyhow = "1"
tokio = "1.20"
enum_dispatch = "0.3.8"

## Mavlink
mavlink = { version = "0.10.1", features = ["default", "emit-extensions"] }

## GSTREAMER
gstreamer = { version = "0.18", features = ["v1_20"] }

[dev-dependencies]
rand = "0.8.5"

[build-dependencies]
reqwest = { version = "0.11.11", features = ["blocking"] }
vergen = { version = "7.4.1", default-features = false, features = ["build", "git"] }
