name: Deploy unix

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          SUFFIX: linux-desktop

    steps:
    - name: Building ${{ matrix.os }} ${{ matrix.SUFFIX }}
      run: echo "${{ matrix.os }} ${{ matrix.SUFFIX }}"

    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1.0.1
      with:
        toolchain: stable
        target: ${{ matrix.TARGET }}
        override: true

    - name: Install linux libraries
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        uname -a
        sudo apt update
        sudo apt install -y libunwind-dev
        sudo apt install -y libclang-dev openssl
        sudo apt install -y libgstrtspserver-1.0-dev libavahi-glib-dev libavahi-core-dev

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release

    - name: Prepare files
      run: |
        mkdir -p upload
        cp target/${{ matrix.TARGET }}/release/mavlink-camera-manager upload/mavlink-camera-manager-${{ matrix.SUFFIX }}

    - uses: actions/upload-artifact@master
      with:
        name: mavlink-camera-manager-${{ matrix.SUFFIX }}
        path: upload/*

    - uses: svenstaro/upload-release-action@v2
      name: Upload binaries to release
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')}}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: upload/*
        asset_name: mavlink-camera-manager-${{ matrix.SUFFIX }}
        tag: ${{ github.ref }}
        overwrite: true
