name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libraries
      run: |
        sudo apt update
        sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstrtspserver-1.0-dev libclang-dev openssl
    - uses: actions-rs/toolchain@v1.0.1
      with:
        toolchain: stable
        override: true
    - name: Check style
      run: cargo fmt -- --check
    - name: Build
      run: |
        cargo build --verbose
        cargo build --verbose --features=rtsp
    - name: Run tests
      run: |
        cargo test --verbose
    - name: Cargo publish
      if: startsWith(github.ref, 'refs/tags/')
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        cargo package --no-verify
        [[ "$(git describe --tags)" =~ ^[0-9]+.[0-9]+.[0-9]+$ ]] && cargo publish --allow-dirty --token $TOKEN || echo "No tag availale for this commit."
